# Pages CMS Configuration for Life in Weeks
# Official Pages CMS structure: media, content, components

# Content configuration
content:
  # Direct YAML editing for events (recommended for your current structure)
  - name: events
    label: Life Events
    type: file
    path: data/events.yml
    format: yaml
    fields:
      - name: body
        label: Events Timeline
        type: code
        description: Edit your life events directly in YAML format. Be careful with formatting!
        options:
          language: yaml

  # Colors configuration
  - name: colors
    label: Colors Configuration
    type: file
    path: data/colors.yml
    format: yaml
    fields:
      - name: body
        label: Colors YAML
        type: code
        options:
          language: yaml

