content:
  - name: colors
    label: Colors
    type: file
    path: data/colors.json
    format: json
    view:
      fields: [class_name, element, color_name]
    fields:
      - name: class_name
        label: Class Name
        type: string
        description: CSS class name (e.g., berlin, working)
      - name: element
        label: Element Type
        type: string
        options: [border, background-color]
        description: Whether this is a border or background color
      - name: color_name
        label: Color Value
        type: string
        pattern: ^#[0-9A-Fa-f]{6}$|^[a-z]+$
        description: Hex color code
