content:
  - name: styles
    label: Style Classes
    type: file
    path: styles.json # Path to your JSON file
    format: json
    fields:
      - name: items
        type: object
        list: true
        fields:
          - name: class_name
            label: Class Name
            type: string
            description: CSS class name (e.g., berlin, working)
          - name: element
            label: Element Type
            type: string
            description: Whether this is a border or background color
          - name: color_name
            label: Color Value
            type: string
            pattern: ^#[0-9A-Fa-f]{6}$|^[a-z]+$
            description: Hex color code
