content:
  - name: content
    label: Content
    type: file
    path: data/content.json # Path to your JSON file
    format: json
    fields:
      - name: colors
        label: Style Classes
        type: object
        list: true
        fields:
          - name: class_name
            label: Class Name
            type: string
          - name: element
            label: Element Type
            type: select
            options:
              values: [border, background-color]
          - name: color_name
            label: Color Value
            type: string
            pattern: ^#[0-9A-Fa-f]{6}$|^[a-z]+$

  - name: content
    label: Events
    type: file
    path: data/content.json # Path to your JSON file
    format: json
    fields:
      - name: events
        label: Life Events
        type: object
        list: true
        fields:
          - name: date
            label: Date
            type: date
          - name: headline
            label: Headline
            type: string
          - name: description
            label: Description
            type: text
            required: false
          - name: based
            label: Based In
            type: string
            required: false
          - name: doing
            label: Activity
            type: string
            required: false
