# Pages CMS Configuration for Life in Weeks
# Official Pages CMS structure: media, content, components

# Content configuration
content:
  # Direct YAML editing for events (recommended for your current structure)
  - name: events
    label: Life Events
    type: file
    path: data/events.yml
    format: yaml
    fields:
      - name: body
        label: Events Timeline
        type: code
        description: Edit your life events directly in YAML format. Be careful with formatting!
        options:
          language: yaml

  # Colors configuration
  - name: colors
    label: Colors Configuration
    type: file
    path: data/colors.yml
    format: yaml
    fields:
      - name: body
        label: Colors YAML
        type: code
        options:
          language: yaml

  # Hugo configuration
  - name: hugo_config
    label: Hugo Configuration
    type: file
    path: hugo.toml
    format: toml
    fields:
      - name: body
        label: Hugo Config
        type: code
        options:
          language: toml

  # Alternative: Individual events as separate files (if you want to restructure)
  - name: individual_events
    label: Individual Events
    type: collection
    path: content/events
    format: yaml-frontmatter
    filename: '{year}-{month}-{day}-{title}'
    fields:
      - name: title
        label: Headline
        type: string
        required: true
        description: Main title for the event (include emoji if desired)
      - name: date
        label: Date
        type: date
        required: true
      - name: description
        label: Description
        type: text
        description: Optional detailed description of the event
      - name: based
        label: Location
        type: string
        description: Where you were based during this event
      - name: doing
        label: Activity
        type: string
        description: What you were doing during this time
      - name: tags
        label: Tags
        type: string
        list: true
        description: Optional tags to categorize your events

# Components (reusable field groups)
components:
  event:
    label: Life Event
    type: object
    fields:
      - name: headline
        label: Headline
        type: string
        required: true
        description: Main title for the event (include emoji if desired)
      - name: description
        label: Description
        type: text
        description: Optional detailed description of the event
      - name: based
        label: Location
        type: string
        description: Where you were based during this event
      - name: doing
        label: Activity
        type: string
        description: What you were doing during this time
